# Generated by Django 2.1.1 on 2019-01-30 18:35

import blog.file_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('img_path', models.ImageField(storage=blog.file_funcs.ImageStorage(), upload_to='img', verbose_name='路径')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
